import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { createAdminCategory, deleteAdminCategory, getAdminCategories, updateAdminCategory } from '../services/admin';

export function CategoryPickerModal({ visible, categories, value, onClose, onSelect, onManage }) {
    return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={styles.shade} onPress={onClose}><Pressable style={styles.sheet} onPress={() => {}}><View style={styles.handle} /><View style={styles.header}><View><Text style={styles.eyebrow}>MOVIE CATEGORY</Text><Text style={styles.title}>Choose a category</Text></View><Pressable style={styles.close} onPress={onClose}><Ionicons name="close" size={22} color="#fff" /></Pressable></View><FlatList data={categories} keyExtractor={(item) => String(item.id)} style={styles.pickerList} renderItem={({ item }) => <Pressable style={[styles.pickRow, value === item.name && styles.pickRowActive]} onPress={() => { onSelect(item.name); onClose(); }}><View style={[styles.categoryIcon, value === item.name && styles.categoryIconActive]}><Ionicons name="grid-outline" size={18} color={value === item.name ? '#fff' : '#aaa'} /></View><View style={styles.categoryCopy}><Text style={styles.categoryName}>{item.name}</Text><Text style={styles.categoryMeta}>{item.movieCount || 0} movie{item.movieCount === 1 ? '' : 's'}{item.protected ? ' · Screenly category' : ' · Custom'}</Text></View>{value === item.name ? <Ionicons name="checkmark-circle" size={23} color="#e50914" /> : <Ionicons name="chevron-forward" size={18} color="#555" />}</Pressable>} /><Pressable style={styles.manageButton} onPress={() => { onClose(); onManage(); }}><Ionicons name="settings-outline" size={19} color="#fff" /><Text style={styles.manageText}>Manage Categories</Text></Pressable></Pressable></Pressable></Modal>;
}

export default function CategoryManagerModal({ visible, onClose, onChanged }) {
    const [categories, setCategories] = useState([]);
    const [loading, setLoading] = useState(false);
    const [saving, setSaving] = useState(false);
    const [editing, setEditing] = useState(null);
    const [name, setName] = useState('');
    const [description, setDescription] = useState('');

    const load = useCallback(async () => {
        setLoading(true);
        try { const items = await getAdminCategories(); setCategories(items); onChanged?.(items); }
        catch (error) { Alert.alert('Categories unavailable', error.message); }
        finally { setLoading(false); }
    }, [onChanged]);
    useEffect(() => { if (visible) load(); }, [visible, load]);

    const resetForm = () => { setEditing(null); setName(''); setDescription(''); };
    const edit = (category) => { setEditing(category); setName(category.name); setDescription(category.description || ''); };
    const save = async () => {
        if (name.trim().length < 2) { Alert.alert('Add a category name', 'Use at least two characters.'); return; }
        setSaving(true);
        try {
            if (editing) await updateAdminCategory(editing.id, { name, description });
            else await createAdminCategory({ name, description });
            resetForm(); await load();
        } catch (error) { Alert.alert(editing ? 'Category not updated' : 'Category not created', error.message); }
        finally { setSaving(false); }
    };
    const remove = (category) => {
        if (category.protected) { Alert.alert('This category stays', 'Screenly’s original categories are always available.'); return; }
        if (category.movieCount) { Alert.alert('Category is in use', `Move ${category.movieCount} movie${category.movieCount === 1 ? '' : 's'} to another category first.`); return; }
        Alert.alert('Remove category?', `${category.name} will no longer appear when adding movies.`, [{ text: 'Keep', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: async () => { try { await deleteAdminCategory(category.id); if (editing?.id === category.id) resetForm(); await load(); } catch (error) { Alert.alert('Category not removed', error.message); } } }]);
    };

    return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={styles.shade} onPress={onClose}><Pressable style={[styles.sheet, styles.managerSheet]} onPress={() => {}}><View style={styles.handle} /><View style={styles.header}><View><Text style={styles.eyebrow}>SCREENLY CONSOLE</Text><Text style={styles.title}>Manage Categories</Text></View><Pressable style={styles.close} onPress={onClose}><Ionicons name="close" size={22} color="#fff" /></Pressable></View><View style={styles.form}><Text style={styles.formTitle}>{editing ? 'Edit custom category' : 'Create a category'}</Text><TextInput value={name} onChangeText={setName} placeholder="Category name" placeholderTextColor="#666" style={styles.input} maxLength={60} /><TextInput value={description} onChangeText={setDescription} placeholder="Short description (optional)" placeholderTextColor="#666" style={[styles.input, styles.description]} maxLength={240} multiline /><View style={styles.formActions}>{editing ? <Pressable style={styles.cancelEdit} onPress={resetForm}><Text style={styles.cancelEditText}>Cancel</Text></Pressable> : null}<Pressable style={[styles.save, saving && styles.disabled]} disabled={saving} onPress={save}>{saving ? <ActivityIndicator color="#fff" /> : <><Ionicons name={editing ? 'checkmark' : 'add'} size={18} color="#fff" /><Text style={styles.saveText}>{editing ? 'Save Changes' : 'Create Category'}</Text></>}</Pressable></View></View><View style={styles.listHeader}><Text style={styles.listTitle}>Available categories</Text><Text style={styles.listCount}>{categories.length}</Text></View>{loading ? <ActivityIndicator color="#e50914" style={styles.loader} /> : <FlatList data={categories} keyExtractor={(item) => String(item.id)} style={styles.managerList} renderItem={({ item }) => <View style={styles.manageRow}><View style={[styles.categoryIcon, item.protected && styles.protectedIcon]}><Ionicons name={item.protected ? 'lock-closed' : 'grid-outline'} size={17} color={item.protected ? '#b2aaff' : '#aaa'} /></View><View style={styles.categoryCopy}><View style={styles.nameRow}><Text style={styles.categoryName}>{item.name}</Text>{item.protected ? <Text style={styles.builtIn}>BUILT-IN</Text> : null}</View><Text style={styles.categoryMeta}>{item.movieCount || 0} movie{item.movieCount === 1 ? '' : 's'}{item.description ? ` · ${item.description}` : ''}</Text></View>{!item.protected ? <><Pressable style={styles.rowAction} hitSlop={8} onPress={() => edit(item)}><Ionicons name="create-outline" size={20} color="#ccc" /></Pressable><Pressable style={styles.rowAction} hitSlop={8} onPress={() => remove(item)}><Ionicons name={item.movieCount ? 'lock-closed-outline' : 'trash-outline'} size={19} color={item.movieCount ? '#666' : '#ff737a'} /></Pressable></> : null}</View>} />}</Pressable></Pressable></Modal>;
}

const styles = StyleSheet.create({
    shade: { flex: 1, backgroundColor: 'rgba(0,0,0,0.72)', justifyContent: 'flex-end' }, sheet: { maxHeight: '82%', backgroundColor: '#14151a', borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 18, paddingTop: 10, paddingBottom: 25 }, managerSheet: { height: '90%', maxHeight: '90%' }, handle: { width: 42, height: 4, borderRadius: 2, backgroundColor: '#3b3d46', alignSelf: 'center' }, header: { minHeight: 78, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, eyebrow: { color: '#e50914', fontSize: 9, fontWeight: '900', letterSpacing: 1.4 }, title: { color: '#fff', fontSize: 22, fontWeight: '900', marginTop: 3 }, close: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#272830', alignItems: 'center', justifyContent: 'center' },
    pickerList: { marginBottom: 13 }, pickRow: { minHeight: 68, borderBottomWidth: 1, borderBottomColor: '#282a31', flexDirection: 'row', alignItems: 'center', gap: 11 }, pickRowActive: { backgroundColor: '#1d1b20' }, categoryIcon: { width: 39, height: 39, borderRadius: 11, backgroundColor: '#272830', alignItems: 'center', justifyContent: 'center' }, categoryIconActive: { backgroundColor: '#e50914' }, protectedIcon: { backgroundColor: '#26223f' }, categoryCopy: { flex: 1 }, categoryName: { color: '#fff', fontSize: 13, fontWeight: '900' }, categoryMeta: { color: '#686b76', fontSize: 9, marginTop: 4 }, manageButton: { height: 48, borderRadius: 10, backgroundColor: '#292b33', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, manageText: { color: '#fff', fontSize: 12, fontWeight: '900' },
    form: { borderRadius: 13, backgroundColor: '#1b1c22', borderWidth: 1, borderColor: '#2c2e36', padding: 13 }, formTitle: { color: '#fff', fontSize: 13, fontWeight: '900', marginBottom: 9 }, input: { minHeight: 44, borderRadius: 8, backgroundColor: '#25262d', borderWidth: 1, borderColor: '#343640', color: '#fff', paddingHorizontal: 12, fontSize: 12, marginBottom: 8 }, description: { height: 62, paddingTop: 10, textAlignVertical: 'top' }, formActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 }, cancelEdit: { height: 39, borderRadius: 8, paddingHorizontal: 15, backgroundColor: '#2a2b32', alignItems: 'center', justifyContent: 'center' }, cancelEditText: { color: '#ddd', fontSize: 11, fontWeight: '800' }, save: { minWidth: 142, height: 39, borderRadius: 8, paddingHorizontal: 14, backgroundColor: '#e50914', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, saveText: { color: '#fff', fontSize: 11, fontWeight: '900' }, disabled: { opacity: 0.6 }, listHeader: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 18, marginBottom: 7 }, listTitle: { color: '#fff', fontSize: 15, fontWeight: '900' }, listCount: { color: '#9c9fab', fontSize: 10, fontWeight: '900', backgroundColor: '#292b33', borderRadius: 9, paddingHorizontal: 7, paddingVertical: 3 }, loader: { marginTop: 35 }, managerList: { flex: 1 }, manageRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: 1, borderBottomColor: '#272930' }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 }, builtIn: { color: '#afa7ff', backgroundColor: '#27233e', borderRadius: 3, paddingHorizontal: 5, paddingVertical: 2, fontSize: 7, fontWeight: '900' }, rowAction: { width: 34, height: 38, alignItems: 'center', justifyContent: 'center' },
});
